# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: API Testing CI

on: [push, pull_request]  # 在 push 和 pull request 触发 CI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run API Tests
        run: pytest ./tests/test_api.py --junitxml=report.xml

      - name: Run API Tests Report
        run: pytest ./tests/test_api.py --html=report.html

      - name: Run API Tests Cov
        run: pytest ./tests/test_api.py --cov --cov-report=html
